// Civic Events Seed Data — Ellis County, TX
import { CivicEvent, EventSource } from '@/lib/types/civic-events';

export const EVENT_SOURCES: EventSource[] = [
    { id: 'src-1', name: 'Ellis County Official Website', url: 'https://www.co.ellis.tx.us', type: 'government', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 12 },
    { id: 'src-2', name: 'City of Waxahachie', url: 'https://www.waxahachie.com', type: 'government', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 8 },
    { id: 'src-3', name: 'City of Midlothian', url: 'https://www.midlothian.tx.us', type: 'government', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 6 },
    { id: 'src-4', name: 'City of Red Oak', url: 'https://www.redoaktx.org', type: 'government', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 4 },
    { id: 'src-5', name: 'City of Ennis', url: 'https://www.ennis-texas.com', type: 'government', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 4 },
    { id: 'src-6', name: 'Waxahachie ISD', url: 'https://www.wisd.org', type: 'education', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 4 },
    { id: 'src-7', name: 'Midlothian ISD', url: 'https://www.misd.gs', type: 'education', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-8', name: 'Red Oak ISD', url: 'https://www.redoakisd.org', type: 'education', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-9', name: 'Ennis ISD', url: 'https://www.ennisisd.org', type: 'education', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 2 },
    { id: 'src-10', name: 'Texas Secretary of State', url: 'https://www.sos.texas.gov/elections', type: 'state', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 5 },
    { id: 'src-11', name: 'Ellis County Republican Party', url: 'https://www.elliscountygop.org', type: 'party', lastChecked: '2026-04-11T18:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-12', name: 'Ellis County Democratic Party', url: 'https://www.elliscountydemocrats.org', type: 'party', lastChecked: '2026-04-11T18:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-13', name: 'Ballotpedia', url: 'https://ballotpedia.org/Ellis_County,_Texas', type: 'state', lastChecked: '2026-04-11T06:00:00Z', status: 'active', eventsCount: 2 },
    { id: 'src-14', name: 'City of Ferris', url: 'https://www.ferristexas.org', type: 'government', lastChecked: '2026-04-10T06:00:00Z', status: 'stale', eventsCount: 2 },
    { id: 'src-15', name: 'City of Palmer', url: 'https://www.palmertexas.com', type: 'government', lastChecked: '2026-04-09T06:00:00Z', status: 'stale', eventsCount: 1 },
];

export const SEED_CIVIC_EVENTS: CivicEvent[] = [

    // ─── ELECTION DATES ──────────────────────────────────────────
    {
        id: 'ce-elect-1', title: '2026 Texas Primary Election Day',
        description: 'Texas Republican and Democratic Primary Election. Ellis County voters will choose party nominees for US Senate, US House, Texas Legislature, and local county offices including County Judge, District Attorney, and Commissioners. Polls open 7am–7pm.',
        date: '2026-05-05', startTime: '07:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Election Precincts', address: 'Various Locations', city: 'Ellis County', state: 'TX', zip: '75165', mapUrl: 'https://www.co.ellis.tx.us/elections' },
        eventType: 'election_date', governingBody: 'Ellis County Elections Administration',
        participationInstructions: 'Bring valid Texas photo ID. Find your polling location at VoterPortal.SOS.State.TX.US. Early voting runs April 27 – May 1.',
        agendaUrl: 'https://www.sos.texas.gov/elections',
        rsvpCount: 0, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['election', 'primary', '2026', 'texas', 'voting'],
        sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-elect-2', title: '2026 Texas Primary Runoff Election',
        description: 'Texas Primary Runoff Election for any races where no candidate received more than 50% of the primary vote. Covers federal, state, and county offices. Polls open 7am–7pm.',
        date: '2026-07-14', startTime: '07:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Election Precincts', address: 'Various Locations', city: 'Ellis County', state: 'TX', zip: '75165', mapUrl: 'https://www.co.ellis.tx.us/elections' },
        eventType: 'election_date', governingBody: 'Ellis County Elections Administration',
        participationInstructions: 'Must have voted in the primary to participate in that party\'s runoff. Bring valid Texas photo ID.',
        agendaUrl: 'https://www.sos.texas.gov/elections',
        rsvpCount: 0, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['election', 'runoff', '2026', 'texas', 'voting'],
        sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-elect-3', title: '2026 Texas General Election Day',
        description: 'Texas General Election covering US Senate seat, all US House seats, Texas Governor (for any vacancy), state legislature, county judge, commissioners, district attorney, sheriff, and judges. Polls open 7am–7pm. Early voting runs October 19–30.',
        date: '2026-11-03', startTime: '07:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Election Precincts', address: 'Various Locations', city: 'Ellis County', state: 'TX', zip: '75165', mapUrl: 'https://www.co.ellis.tx.us/elections' },
        eventType: 'election_date', governingBody: 'Ellis County Elections Administration',
        participationInstructions: 'Voter registration deadline is October 5. Bring valid Texas photo ID. Find your polling place at VoterPortal.SOS.State.TX.US.',
        agendaUrl: 'https://www.sos.texas.gov/elections',
        rsvpCount: 0, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['election', 'general-election', '2026', 'texas', 'voting', 'november'],
        sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-elect-4', title: 'Election Early Voting — May Primary',
        description: 'Early voting period for the May 2026 Texas Primary Election. Vote at any Ellis County early voting location during this window. No need to visit your assigned precinct.',
        date: '2026-04-27', startTime: '07:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Early Voting Locations', address: 'Various — See sos.texas.gov', city: 'Ellis County', state: 'TX', zip: '75165', mapUrl: 'https://www.co.ellis.tx.us/elections' },
        eventType: 'election_date', governingBody: 'Ellis County Elections Administration',
        participationInstructions: 'Early voting runs April 27 – May 1. Any registered Ellis County voter may vote at any early voting site.',
        rsvpCount: 0, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['early-voting', 'primary', '2026', 'voting'],
        sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Debates & Candidate Forums ───────────────────────────────
    {
        id: 'ce-debate-1', title: 'Candidate Debate — Ellis County Judge',
        description: 'Live candidate debate between the Republican and Democratic nominees for Ellis County Judge. Three-minute opening statements, issue-based questions, and audience Q&A. Hosted by Pivotal Voice in partnership with the Ellis County Bar Association.',
        date: '2026-09-22', startTime: '18:30', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Civic Center', address: '2200 Civic Center Ln', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=2200+Civic+Center+Ln+Waxahachie+TX' },
        eventType: 'debate', governingBody: 'Pivotal Voice / Ellis County Bar Association',
        participationInstructions: 'Submit questions at pivotalvoice.com/events or on 3x5 cards at the venue. Doors open at 6:00 PM. Free admission.',
        zoomUrl: 'https://zoom.us/j/elliscountyjudgedebate',
        rsvpCount: 52, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['debate', 'county-judge', 'waxahachie', 'general-election'],
        sourceUrl: 'https://pivotalvoice.com/events', sourceName: 'Pivotal Voice',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-debate-2', title: 'Candidate Debate — Texas State Rep. District 10',
        description: 'Head-to-head debate between candidates for Texas House of Representatives District 10. Topics include water policy, school funding, and property tax reform. Moderated by local journalists.',
        date: '2026-10-06', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Midlothian Conference Center', address: '1 Community Circle Dr', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=1+Community+Circle+Dr+Midlothian+TX' },
        eventType: 'debate', governingBody: 'Pivotal Voice / League of Women Voters',
        participationInstructions: 'Open to all residents of HD-10. Submit questions online by October 4.',
        rsvpCount: 38, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['debate', 'state-rep', 'district-10', 'midlothian'],
        sourceUrl: 'https://pivotalvoice.com/events', sourceName: 'Pivotal Voice',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-forum-1', title: 'Candidate Forum — Waxahachie City Council District 3',
        description: 'Moderated candidate forum for the District 3 city council race. Three candidates will present their platforms and answer questions from voters and the moderating panel.',
        date: '2026-04-28', startTime: '18:30', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Civic Center', address: '2200 Civic Center Ln', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=2200+Civic+Center+Ln+Waxahachie+TX' },
        eventType: 'candidate_forum', governingBody: 'Pivotal Voice / League of Women Voters',
        participationInstructions: 'Submit questions in advance at pivotalvoice.com or write them on cards at the event. Doors open at 6:00 PM.',
        rsvpCount: 45, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['city-council', 'candidate-forum', 'waxahachie', 'district-3'],
        sourceUrl: 'https://pivotalvoice.com/events', sourceName: 'Pivotal Voice',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-forum-2', title: 'Meet & Greet — State Rep. District 10 Candidates',
        description: 'Informal meet and greet with candidates running for Texas State Representative District 10. Light refreshments provided. Great opportunity to ask direct questions.',
        date: '2026-04-22', startTime: '14:00', endTime: '16:00', timezone: 'America/Chicago',
        location: { name: 'Midlothian Community Park Pavilion', address: '4000 Community Center Dr', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=4000+Community+Center+Dr+Midlothian+TX' },
        eventType: 'meet_greet',
        participationInstructions: 'Open to all community members. Family-friendly event.',
        rsvpCount: 28, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['state-rep', 'meet-greet', 'midlothian', 'district-10'],
        sourceUrl: 'https://www.elliscountygop.org', sourceName: 'Ellis County Republican Party',
        lastVerified: '2026-04-11T18:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Town Halls ──────────────────────────────────────────────
    {
        id: 'ce-town-1', title: 'Town Hall — Property Tax Reform',
        description: 'Town hall hosted by County Commissioner Precinct 2 on property tax reform proposals and the impact on Ellis County homeowners. Public Q&A session included.',
        date: '2026-04-23', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Red Oak Community Center', address: '100 Community Dr', city: 'Red Oak', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=Red+Oak+Community+Center+TX' },
        eventType: 'town_hall', governingBody: 'Ellis County Commissioner Precinct 2',
        zoomUrl: 'https://zoom.us/j/property-tax-townhall',
        participationInstructions: 'In-person and virtual attendance options. Submit questions online at co.ellis.tx.us or ask during the Q&A period.',
        rsvpCount: 38, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['property-tax', 'town-hall', 'red-oak', 'budget'],
        sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-town-2', title: 'Town Hall — I-35E Expansion Impact on Ellis County',
        description: 'Public town hall on TxDOT\'s proposed I-35E expansion and its impact on Midlothian and Red Oak neighborhoods. TXDOT representatives will present plans and answer resident questions.',
        date: '2026-05-12', startTime: '18:30', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Midlothian Conference Center', address: '1 Community Circle Dr', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=1+Community+Circle+Dr+Midlothian+TX' },
        eventType: 'town_hall', governingBody: 'TxDOT / Ellis County Commissioners',
        participationInstructions: 'Public comment period open. Written comments also accepted at txdot.gov. All residents welcome.',
        rsvpCount: 61, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['i-35e', 'infrastructure', 'txdot', 'midlothian', 'town-hall'],
        sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-town-3', title: 'Town Hall — Water Supply & Drought Planning',
        description: 'Ellis County and area city managers will present the county\'s 10-year water supply plan. Includes drought contingency measures, reservoir capacity, and impact on residential development.',
        date: '2026-06-09', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Civic Center', address: '2200 Civic Center Ln', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=2200+Civic+Center+Ln+Waxahachie+TX' },
        eventType: 'town_hall', governingBody: 'Ellis County Water District',
        zoomUrl: 'https://zoom.us/j/elliscountywaterhall',
        participationInstructions: 'Open to all county residents. Sign up to speak at the public comment period at co.ellis.tx.us.',
        rsvpCount: 44, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['water', 'drought', 'planning', 'waxahachie', 'town-hall'],
        sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Ellis County Commissioners Court ────────────────────────
    {
        id: 'ce-1', title: 'Ellis County Commissioners Court — Regular Session',
        description: 'Regular session of the Ellis County Commissioners Court. Agenda items include county budget amendments, road maintenance contracts, and EMS service agreements.',
        date: '2026-04-13', startTime: '10:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Courthouse', address: '101 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=101+W+Main+St+Waxahachie+TX' },
        eventType: 'commissioners_court', governingBody: 'Ellis County Commissioners Court',
        agendaUrl: 'https://www.co.ellis.tx.us/AgendaCenter', minutesUrl: 'https://www.co.ellis.tx.us/Archive',
        participationInstructions: 'Public comment period at the beginning of each session. Sign up at the clerk\'s desk before the meeting begins. Each speaker gets 3 minutes.',
        rsvpCount: 12, rsvpUsers: [], isFeatured: true, isRecurring: true, recurringSchedule: '2nd and 4th Monday',
        tags: ['budget', 'roads', 'ems'], sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-2', title: 'Ellis County Commissioners Court — Budget Workshop',
        description: 'Special budget workshop to review proposed FY2027 budget priorities, including infrastructure spending, law enforcement staffing, and public health initiatives.',
        date: '2026-04-27', startTime: '09:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Courthouse', address: '101 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: ' https://maps.google.com/?q=101+W+Main+St+Waxahachie+TX' },
        eventType: 'commissioners_court', governingBody: 'Ellis County Commissioners Court',
        agendaUrl: 'https://www.co.ellis.tx.us/AgendaCenter',
        participationInstructions: 'This is a workshop session. Public comment is not typically taken during workshops, but observers are welcome.',
        rsvpCount: 8, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['budget', 'infrastructure', 'public-health'], sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-cc-may', title: 'Ellis County Commissioners Court — Regular Session',
        description: 'Regular bi-monthly session. Agenda includes May election logistics, county road resurfacing contracts Precincts 2 & 3, and EMS quarterly report.',
        date: '2026-05-11', startTime: '10:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Courthouse', address: '101 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=101+W+Main+St+Waxahachie+TX' },
        eventType: 'commissioners_court', governingBody: 'Ellis County Commissioners Court',
        agendaUrl: 'https://www.co.ellis.tx.us/AgendaCenter',
        participationInstructions: 'Public comment at start of session. Sign up at clerk\'s desk before 10:00 AM.',
        rsvpCount: 9, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd and 4th Monday',
        tags: ['budget', 'roads', 'elections'], sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── City Council Meetings ───────────────────────────────────
    {
        id: 'ce-3', title: 'Waxahachie City Council — Regular Meeting',
        description: 'Regular meeting of the Waxahachie City Council. Key items: downtown parking ordinance update, utility rate review, and parks master plan presentation.',
        date: '2026-04-20', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie City Hall', address: '401 S Rogers St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=401+S+Rogers+St+Waxahachie+TX' },
        eventType: 'city_council', governingBody: 'Waxahachie City Council',
        agendaUrl: 'https://www.waxahachie.com/AgendaCenter', zoomUrl: 'https://zoom.us/j/waxahachie-council',
        participationInstructions: 'Public comment at the beginning. Sign up online by 4:00 PM on meeting day or in person at City Hall. Virtual attendance available via Zoom.',
        rsvpCount: 18, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '1st and 3rd Monday',
        tags: ['parking', 'utilities', 'parks'], sourceUrl: 'https://www.waxahachie.com', sourceName: 'City of Waxahachie',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-4', title: 'Midlothian City Council — Regular Meeting',
        description: 'Regular session. Agenda includes zoning variance requests for Heritage Crossing development, water infrastructure bond discussion, and fire department staffing.',
        date: '2026-04-14', startTime: '18:30', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Midlothian City Hall', address: '104 W Ave E', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=104+W+Ave+E+Midlothian+TX' },
        eventType: 'city_council', governingBody: 'Midlothian City Council',
        agendaUrl: 'https://www.midlothian.tx.us/AgendaCenter',
        participationInstructions: 'Citizens may address the Council during the public hearing portion. Register at the podium before the meeting.',
        rsvpCount: 14, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd and 4th Tuesday',
        tags: ['zoning', 'water', 'fire-department'], sourceUrl: 'https://www.midlothian.tx.us', sourceName: 'City of Midlothian',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-5', title: 'Red Oak City Council — Regular Meeting',
        description: 'Regular meeting. Agenda: comprehensive plan update, annexation discussion for Ovilla Road corridor, and police department capital improvements.',
        date: '2026-04-23', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Red Oak Municipal Center', address: '200 Lakeview Pkwy', city: 'Red Oak', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=200+Lakeview+Pkwy+Red+Oak+TX' },
        eventType: 'city_council', governingBody: 'Red Oak City Council',
        agendaUrl: 'https://www.redoaktx.org/AgendaCenter',
        participationInstructions: 'Public comment cards available at the entrance. Submit before the meeting starts.',
        rsvpCount: 9, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd and 4th Thursday',
        tags: ['comprehensive-plan', 'annexation', 'police'], sourceUrl: 'https://www.redoaktx.org', sourceName: 'City of Red Oak',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-6', title: 'Ennis City Council — Regular Meeting',
        description: 'Regular session covering downtown revitalization grants, wastewater treatment plant expansion, and Bluebonnet Trail festival planning.',
        date: '2026-04-21', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Ennis City Hall', address: '115 W Brown St', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=115+W+Brown+St+Ennis+TX' },
        eventType: 'city_council', governingBody: 'Ennis City Council',
        agendaUrl: 'https://www.ennis-texas.com/agendas',
        participationInstructions: 'Public hearing comments welcome. Sign up with the city secretary before the meeting.',
        rsvpCount: 7, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '1st and 3rd Tuesday',
        tags: ['downtown', 'wastewater', 'festival'], sourceUrl: 'https://www.ennis-texas.com', sourceName: 'City of Ennis',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-7', title: 'Ferris City Council — Regular Meeting',
        description: 'Agenda includes I-45 corridor development, water system upgrades, and animal control ordinance revisions.',
        date: '2026-04-20', startTime: '19:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Ferris City Hall', address: '110 S Central St', city: 'Ferris', state: 'TX', zip: '75125', mapUrl: 'https://maps.google.com/?q=110+S+Central+St+Ferris+TX' },
        eventType: 'city_council', governingBody: 'Ferris City Council',
        participationInstructions: 'Public comments at start of meeting.',
        rsvpCount: 4, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['i-45', 'water', 'ordinances'], sourceUrl: 'https://www.ferristexas.org', sourceName: 'City of Ferris',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-8', title: 'Palmer City Council — Regular Meeting',
        description: 'Regular meeting addressing road maintenance, volunteer fire department budget, and community center improvements.',
        date: '2026-04-16', startTime: '18:30', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Palmer City Hall', address: '302 Shelton St', city: 'Palmer', state: 'TX', zip: '75152', mapUrl: 'https://maps.google.com/?q=302+Shelton+St+Palmer+TX' },
        eventType: 'city_council', governingBody: 'Palmer City Council',
        participationInstructions: 'Open public comment period.',
        rsvpCount: 3, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['roads', 'fire-department', 'community-center'], sourceUrl: 'https://www.palmertexas.com', sourceName: 'City of Palmer',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-9', title: 'Italy City Council — Regular Meeting',
        description: 'Agenda covers street repair program, utility billing updates, and economic development incentive review.',
        date: '2026-04-20', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Italy City Hall', address: '100 N Ward St', city: 'Italy', state: 'TX', zip: '76651', mapUrl: 'https://maps.google.com/?q=100+N+Ward+St+Italy+TX' },
        eventType: 'city_council', governingBody: 'Italy City Council',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['streets', 'utilities', 'economic-dev'], sourceUrl: 'https://www.italytx.org', sourceName: 'City of Italy',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-10', title: 'Ovilla City Council — Regular Meeting',
        description: 'Topics include rural preservation ordinance discussion, volunteer opportunities, and park trail expansion.',
        date: '2026-04-21', startTime: '19:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Ovilla City Hall', address: '105 N Cockrell Hill Rd', city: 'Ovilla', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=105+N+Cockrell+Hill+Rd+Ovilla+TX' },
        eventType: 'city_council', governingBody: 'Ovilla City Council',
        rsvpCount: 5, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Tuesday',
        tags: ['rural-preservation', 'parks', 'volunteer'], sourceUrl: 'https://www.ovillatx.gov', sourceName: 'City of Ovilla',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── School Board Meetings ───────────────────────────────────
    {
        id: 'ce-11', title: 'Waxahachie ISD Board — Regular Meeting',
        description: 'Board meeting: teacher hiring update, bond proposal for new elementary school, and STAAR score analysis. Public comment at 6:30 PM.',
        date: '2026-04-20', startTime: '18:30', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'WISD Administration Building', address: '411 N Gibson St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=411+N+Gibson+St+Waxahachie+TX' },
        eventType: 'school_board', governingBody: 'Waxahachie ISD Board of Trustees',
        agendaUrl: 'https://www.wisd.org/Page/BoardAgendas', zoomUrl: 'https://zoom.us/j/wisd-board',
        participationInstructions: 'Public comment period at 6:30 PM. Register online by noon on meeting day or in person. Each speaker gets 3 minutes.',
        rsvpCount: 22, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['teachers', 'bond', 'staar-scores'], sourceUrl: 'https://www.wisd.org', sourceName: 'Waxahachie ISD',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-12', title: 'Midlothian ISD Board — Regular Meeting',
        description: 'Agenda includes CTE program expansion, facilities assessment, and student enrollment projections for 2026-27.',
        date: '2026-04-16', startTime: '18:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'MISD Administration Building', address: '100 Walter Stephenson Rd', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=100+Walter+Stephenson+Rd+Midlothian+TX' },
        eventType: 'school_board', governingBody: 'Midlothian ISD Board of Trustees',
        agendaUrl: 'https://www.misd.gs/BoardAgendas',
        participationInstructions: 'Open public comment. Sign up in the lobby before 6:00 PM.',
        rsvpCount: 16, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['cte', 'facilities', 'enrollment'], sourceUrl: 'https://www.misd.gs', sourceName: 'Midlothian ISD',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-13', title: 'Red Oak ISD Board — Regular Meeting',
        description: 'Topics include athletic facility improvements, teacher retention incentives, and budget amendments.',
        date: '2026-04-20', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'ROISD Administration Building', address: '3108 S Houston School Rd', city: 'Red Oak', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=3108+S+Houston+School+Rd+Red+Oak+TX' },
        eventType: 'school_board', governingBody: 'Red Oak ISD Board of Trustees',
        rsvpCount: 11, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['athletics', 'teacher-retention', 'budget'], sourceUrl: 'https://www.redoakisd.org', sourceName: 'Red Oak ISD',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-14', title: 'Ennis ISD Board — Regular Meeting',
        description: 'Board agenda: dual-language program update, maintenance bond reauthorization, and food service contract.',
        date: '2026-04-16', startTime: '18:30', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Ennis ISD Administration', address: '303 W Knox St', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=303+W+Knox+St+Ennis+TX' },
        eventType: 'school_board', governingBody: 'Ennis ISD Board of Trustees',
        rsvpCount: 8, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['dual-language', 'maintenance', 'food-service'], sourceUrl: 'https://www.ennisisd.org', sourceName: 'Ennis ISD',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-15', title: 'Ferris ISD Board — Regular Meeting',
        description: 'Discussion on school security upgrades, staff compensation study, and technology refresh.',
        date: '2026-04-15', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Ferris ISD Admin', address: '216 E 8th St', city: 'Ferris', state: 'TX', zip: '75125' },
        eventType: 'school_board', governingBody: 'Ferris ISD Board of Trustees',
        rsvpCount: 5, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Wednesday',
        tags: ['security', 'compensation', 'technology'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
    },

    // ─── Planning & Zoning ────────────────────────────────────────
    {
        id: 'ce-16', title: 'Waxahachie Planning & Zoning Commission',
        description: 'Public hearing on proposed mixed-use development at US-77/I-35E interchange, residential subdivision plats, and sign ordinance amendments.',
        date: '2026-04-16', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie City Hall', address: '401 S Rogers St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=401+S+Rogers+St+Waxahachie+TX' },
        eventType: 'planning_zoning', governingBody: 'Waxahachie P&Z Commission',
        agendaUrl: 'https://www.waxahachie.com/PlanningZoning',
        participationInstructions: 'This is a public hearing. All affected property owners and interested citizens may speak on agenda items.',
        publicCommentDeadline: '2026-04-16T16:00:00Z',
        rsvpCount: 15, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd Thursday',
        tags: ['mixed-use', 'development', 'zoning'], sourceUrl: 'https://www.waxahachie.com', sourceName: 'City of Waxahachie',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-17', title: 'Midlothian Economic Development Corporation — Quarterly Meeting',
        description: 'Quarterly report on business attraction, retention efforts, and incentive agreements. Presentation on broadband expansion initiative.',
        date: '2026-04-28', startTime: '17:30', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Midlothian Conference Center', address: '1 Community Circle Dr', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=1+Community+Circle+Dr+Midlothian+TX' },
        eventType: 'economic_dev', governingBody: 'Midlothian EDC',
        participationInstructions: 'Open to the public. Q&A session after presentations.',
        rsvpCount: 10, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: 'Quarterly',
        tags: ['business', 'broadband', 'incentives'], sourceUrl: 'https://www.midlothian.tx.us', sourceName: 'City of Midlothian',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Political Party Meetings ─────────────────────────────────
    {
        id: 'ce-18', title: 'Ellis County Republican Party — Monthly Meeting',
        description: 'Monthly meeting featuring candidate introductions for upcoming city council races and primary election preparation.',
        date: '2026-04-09', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Civic Center', address: '2200 Civic Center Ln', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=2200+Civic+Center+Ln+Waxahachie+TX' },
        eventType: 'party_meeting', governingBody: 'Ellis County Republican Party',
        participationInstructions: 'Open to all registered Republicans. Membership not required to attend.',
        rsvpCount: 35, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd Thursday',
        tags: ['republican', 'primary', 'candidates'], sourceUrl: 'https://www.elliscountygop.org', sourceName: 'Ellis County Republican Party',
        lastVerified: '2026-04-11T18:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-19', title: 'Ellis County Democratic Party — Monthly Meeting',
        description: 'Monthly meeting with voter mobilization strategy, precinct captain training, and guest speaker on education policy.',
        date: '2026-04-16', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Ennis Public Library', address: '501 W Ennis Ave', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=501+W+Ennis+Ave+Ennis+TX' },
        eventType: 'party_meeting', governingBody: 'Ellis County Democratic Party',
        participationInstructions: 'Open to all Democrats and interested community members.',
        rsvpCount: 22, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['democrat', 'voter-mobilization', 'education'], sourceUrl: 'https://www.elliscountydemocrats.org', sourceName: 'Ellis County Democratic Party',
        lastVerified: '2026-04-11T18:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-04-11T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Voter Registration ───────────────────────────────────────
    {
        id: 'ce-23', title: 'Voter Registration Drive — Ennis',
        description: 'Free voter registration and education event. Bilingual registration assistance available. Bring your Texas ID or last 4 of SSN.',
        date: '2026-04-18', startTime: '10:00', endTime: '14:00', timezone: 'America/Chicago',
        location: { name: 'Ennis Public Library', address: '501 W Ennis Ave', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=501+W+Ennis+Ave+Ennis+TX' },
        eventType: 'voter_registration',
        participationInstructions: 'No appointment needed. Bring a valid Texas driver\'s license or ID, or the last 4 digits of your SSN. Bilingual staff available.',
        rsvpCount: 15, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['voter-registration', 'bilingual', 'ennis'], sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-24', title: 'Voter Registration Drive — Waxahachie Farmers Market',
        description: 'Community voter registration event at the farmers market. Register, check your status, or update your address. Deadline to register for May primary is April 4.',
        date: '2026-04-25', startTime: '08:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Downtown Farmers Market', address: '400 S Rogers St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=400+S+Rogers+St+Waxahachie+TX' },
        eventType: 'voter_registration',
        participationInstructions: 'Stop by the registration booth anytime. Volunteers will assist you with the process.',
        rsvpCount: 8, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['voter-registration', 'farmers-market', 'waxahachie'], sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-04-11T06:00:00Z', createdAt: '2026-04-01T10:00:00Z', updatedAt: '2026-04-11T06:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Community Events ─────────────────────────────────────────
    {
        id: 'lm-02', title: 'Ellis County Conservatives — Coffee & Politics',
        description: 'Morning discussion group focusing on conservative values in local government. Guest speaker: Ellis County Tax Assessor-Collector.',
        date: '2026-04-25', startTime: '09:00', endTime: '10:30', timezone: 'America/Chicago',
        location: { name: 'White Rhino Coffee', address: '414 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=White+Rhino+Coffee+Waxahachie+TX' },
        eventType: 'community_event', governingBody: 'Ellis County Conservatives',
        participationInstructions: 'Free to attend. Coffee available for purchase.',
        rsvpCount: 25, rsvpUsers: [], isFeatured: true, isRecurring: true, recurringSchedule: '4th Saturday',
        tags: ['conservative', 'coffee', 'discussion'],
        lastVerified: '2026-04-11T10:00:00Z', createdAt: '2026-04-11T10:00:00Z', updatedAt: '2026-04-11T10:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'lm-03', title: 'Progressive Voters League — Community Organizing Workshop',
        description: 'Learn effective strategies for community organizing, canvassing, and voter outreach ahead of the May primary.',
        date: '2026-04-19', startTime: '13:00', endTime: '16:00', timezone: 'America/Chicago',
        location: { name: 'Sims Library', address: '515 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=Sims+Library+Waxahachie+TX' },
        eventType: 'community_event', governingBody: 'Progressive Voters League',
        participationInstructions: 'Registration recommended but not required. Materials provided.',
        rsvpCount: 18, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['progressive', 'organizing', 'workshop', 'get-out-the-vote'],
        lastVerified: '2026-04-11T10:00:00Z', createdAt: '2026-04-11T10:00:00Z', updatedAt: '2026-04-11T10:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'lm-04', title: 'Young Republicans — Happy Hour Mixer',
        description: 'Networking event for young professionals interested in Republican politics. Come meet like-minded individuals and discuss the upcoming May primary.',
        date: '2026-04-30', startTime: '17:30', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'College Street Pub', address: '210 N College St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=College+Street+Pub+Waxahachie+TX' },
        eventType: 'party_meeting', governingBody: 'Ellis County Young Republicans',
        participationInstructions: 'Ages 21-40 welcome. Cash bar.',
        rsvpCount: 30, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: 'Last Thursday',
        tags: ['young-republicans', 'networking', 'social'],
        lastVerified: '2026-04-11T10:00:00Z', createdAt: '2026-04-11T10:00:00Z', updatedAt: '2026-04-11T10:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
];

export const LOCAL_MEETUP_EVENTS: CivicEvent[] = [];
