// Civic Events Seed Data — Ellis County, TX
import { CivicEvent, EventSource } from '@/lib/types/civic-events';

export const EVENT_SOURCES: EventSource[] = [
    { id: 'src-1', name: 'Ellis County Official Website', url: 'https://www.co.ellis.tx.us', type: 'government', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 12 },
    { id: 'src-2', name: 'City of Waxahachie', url: 'https://www.waxahachie.com', type: 'government', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 8 },
    { id: 'src-3', name: 'City of Midlothian', url: 'https://www.midlothian.tx.us', type: 'government', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 6 },
    { id: 'src-4', name: 'City of Red Oak', url: 'https://www.redoaktx.org', type: 'government', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 4 },
    { id: 'src-5', name: 'City of Ennis', url: 'https://www.ennis-texas.com', type: 'government', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 4 },
    { id: 'src-6', name: 'Waxahachie ISD', url: 'https://www.wisd.org', type: 'education', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 4 },
    { id: 'src-7', name: 'Midlothian ISD', url: 'https://www.misd.gs', type: 'education', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-8', name: 'Red Oak ISD', url: 'https://www.redoakisd.org', type: 'education', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-9', name: 'Ennis ISD', url: 'https://www.ennisisd.org', type: 'education', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 2 },
    { id: 'src-10', name: 'Texas Secretary of State', url: 'https://www.sos.texas.gov/elections', type: 'state', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 5 },
    { id: 'src-11', name: 'Ellis County Republican Party', url: 'https://www.elliscountygop.org', type: 'party', lastChecked: '2026-02-08T18:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-12', name: 'Ellis County Democratic Party', url: 'https://www.elliscountydemocrats.org', type: 'party', lastChecked: '2026-02-08T18:00:00Z', status: 'active', eventsCount: 3 },
    { id: 'src-13', name: 'Ballotpedia', url: 'https://ballotpedia.org/Ellis_County,_Texas', type: 'state', lastChecked: '2026-02-09T06:00:00Z', status: 'active', eventsCount: 2 },
    { id: 'src-14', name: 'City of Ferris', url: 'https://www.ferristexas.org', type: 'government', lastChecked: '2026-02-08T06:00:00Z', status: 'stale', eventsCount: 2 },
    { id: 'src-15', name: 'City of Palmer', url: 'https://www.palmertexas.com', type: 'government', lastChecked: '2026-02-07T06:00:00Z', status: 'stale', eventsCount: 1 },
];

export const SEED_CIVIC_EVENTS: CivicEvent[] = [
    // ─── Ellis County Commissioners Court ────────────────────
    {
        id: 'ce-1', title: 'Ellis County Commissioners Court — Regular Session',
        description: 'Regular session of the Ellis County Commissioners Court. Agenda items include county budget amendments, road maintenance contracts, and EMS service agreements.',
        date: '2026-02-10', startTime: '10:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Courthouse', address: '101 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=101+W+Main+St+Waxahachie+TX' },
        eventType: 'commissioners_court', governingBody: 'Ellis County Commissioners Court',
        agendaUrl: 'https://www.co.ellis.tx.us/AgendaCenter', minutesUrl: 'https://www.co.ellis.tx.us/Archive',
        participationInstructions: 'Public comment period at the beginning of each session. Sign up at the clerk\'s desk before the meeting begins. Each speaker gets 3 minutes.',
        rsvpCount: 12, rsvpUsers: [], isFeatured: true, isRecurring: true, recurringSchedule: '2nd and 4th Monday',
        tags: ['budget', 'roads', 'ems'], sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-15T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-2', title: 'Ellis County Commissioners Court — Budget Workshop',
        description: 'Special budget workshop to review proposed FY2027 budget priorities, including infrastructure spending, law enforcement staffing, and public health initiatives.',
        date: '2026-02-24', startTime: '09:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Ellis County Courthouse', address: '101 W Main St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=101+W+Main+St+Waxahachie+TX' },
        eventType: 'commissioners_court', governingBody: 'Ellis County Commissioners Court',
        agendaUrl: 'https://www.co.ellis.tx.us/AgendaCenter',
        participationInstructions: 'This is a workshop session. Public comment is not typically taken during workshops, but observers are welcome.',
        rsvpCount: 8, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['budget', 'infrastructure', 'public-health'], sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── City Council Meetings ───────────────────────────────
    {
        id: 'ce-3', title: 'Waxahachie City Council — Regular Meeting',
        description: 'Regular meeting of the Waxahachie City Council. Key items: downtown parking ordinance update, utility rate review, and parks master plan presentation.',
        date: '2026-02-17', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie City Hall', address: '401 S Rogers St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=401+S+Rogers+St+Waxahachie+TX' },
        eventType: 'city_council', governingBody: 'Waxahachie City Council',
        agendaUrl: 'https://www.waxahachie.com/AgendaCenter', zoomUrl: 'https://zoom.us/j/waxahachie-council',
        participationInstructions: 'Public comment at the beginning. Sign up online by 4:00 PM on meeting day or in person at City Hall. Virtual attendance available via Zoom.',
        rsvpCount: 18, rsvpUsers: [], isFeatured: true, isRecurring: true, recurringSchedule: '1st and 3rd Monday',
        tags: ['parking', 'utilities', 'parks'], sourceUrl: 'https://www.waxahachie.com', sourceName: 'City of Waxahachie',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-4', title: 'Midlothian City Council — Regular Meeting',
        description: 'Regular session. Agenda includes zoning variance requests for Heritage Crossing development, water infrastructure bond discussion, and fire department staffing.',
        date: '2026-02-11', startTime: '18:30', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Midlothian City Hall', address: '104 W Ave E', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=104+W+Ave+E+Midlothian+TX' },
        eventType: 'city_council', governingBody: 'Midlothian City Council',
        agendaUrl: 'https://www.midlothian.tx.us/AgendaCenter',
        participationInstructions: 'Citizens may address the Council during the public hearing portion. Register at the podium before the meeting.',
        rsvpCount: 14, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd and 4th Tuesday',
        tags: ['zoning', 'water', 'fire-department'], sourceUrl: 'https://www.midlothian.tx.us', sourceName: 'City of Midlothian',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-5', title: 'Red Oak City Council — Regular Meeting',
        description: 'Regular meeting. Agenda: comprehensive plan update, annexation discussion for Ovilla Road corridor, and police department capital improvements.',
        date: '2026-02-12', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Red Oak Municipal Center', address: '200 Lakeview Pkwy', city: 'Red Oak', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=200+Lakeview+Pkwy+Red+Oak+TX' },
        eventType: 'city_council', governingBody: 'Red Oak City Council',
        agendaUrl: 'https://www.redoaktx.org/AgendaCenter',
        participationInstructions: 'Public comment cards available at the entrance. Submit before the meeting starts.',
        rsvpCount: 9, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd and 4th Thursday',
        tags: ['comprehensive-plan', 'annexation', 'police'], sourceUrl: 'https://www.redoaktx.org', sourceName: 'City of Red Oak',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-6', title: 'Ennis City Council — Regular Meeting',
        description: 'Regular session covering downtown revitalization grants, wastewater treatment plant expansion, and Bluebonnet Trail festival planning.',
        date: '2026-02-18', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Ennis City Hall', address: '115 W Brown St', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=115+W+Brown+St+Ennis+TX' },
        eventType: 'city_council', governingBody: 'Ennis City Council',
        agendaUrl: 'https://www.ennis-texas.com/agendas',
        participationInstructions: 'Public hearing comments welcome. Sign up with the city secretary before the meeting.',
        rsvpCount: 7, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '1st and 3rd Tuesday',
        tags: ['downtown', 'wastewater', 'festival'], sourceUrl: 'https://www.ennis-texas.com', sourceName: 'City of Ennis',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-7', title: 'Ferris City Council — Regular Meeting',
        description: 'Agenda includes I-45 corridor development, water system upgrades, and animal control ordinance revisions.',
        date: '2026-02-17', startTime: '19:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Ferris City Hall', address: '110 S Central St', city: 'Ferris', state: 'TX', zip: '75125', mapUrl: 'https://maps.google.com/?q=110+S+Central+St+Ferris+TX' },
        eventType: 'city_council', governingBody: 'Ferris City Council',
        participationInstructions: 'Public comments at start of meeting.',
        rsvpCount: 4, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['i-45', 'water', 'ordinances'], sourceUrl: 'https://www.ferristexas.org', sourceName: 'City of Ferris',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-8', title: 'Palmer City Council — Regular Meeting',
        description: 'Regular meeting addressing road maintenance, volunteer fire department budget, and community center improvements.',
        date: '2026-02-19', startTime: '18:30', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Palmer City Hall', address: '302 Shelton St', city: 'Palmer', state: 'TX', zip: '75152', mapUrl: 'https://maps.google.com/?q=302+Shelton+St+Palmer+TX' },
        eventType: 'city_council', governingBody: 'Palmer City Council',
        participationInstructions: 'Open public comment period.',
        rsvpCount: 3, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['roads', 'fire-department', 'community-center'], sourceUrl: 'https://www.palmertexas.com', sourceName: 'City of Palmer',
        lastVerified: '2026-02-07T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-06T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-9', title: 'Italy City Council — Regular Meeting',
        description: 'Agenda covers street repair program, utility billing updates, and economic development incentive review.',
        date: '2026-02-16', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Italy City Hall', address: '100 N Ward St', city: 'Italy', state: 'TX', zip: '76651', mapUrl: 'https://maps.google.com/?q=100+N+Ward+St+Italy+TX' },
        eventType: 'city_council', governingBody: 'Italy City Council',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['streets', 'utilities', 'economic-dev'], sourceUrl: 'https://www.italytx.org', sourceName: 'City of Italy',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-10', title: 'Ovilla City Council — Regular Meeting',
        description: 'Topics include rural preservation ordinance discussion, volunteer opportunities, and park trail expansion.',
        date: '2026-02-18', startTime: '19:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Ovilla City Hall', address: '105 N Cockrell Hill Rd', city: 'Ovilla', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=105+N+Cockrell+Hill+Rd+Ovilla+TX' },
        eventType: 'city_council', governingBody: 'Ovilla City Council',
        rsvpCount: 5, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Tuesday',
        tags: ['rural-preservation', 'parks', 'volunteer'], sourceUrl: 'https://www.ovillatx.gov', sourceName: 'City of Ovilla',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-44', title: 'Milford City Council — Regular Meeting',
        description: 'Regular meeting addressing water infrastructure, road improvements, and community safety.',
        date: '2026-02-20', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Milford Community Center', address: '200 E Main St', city: 'Milford', state: 'TX', zip: '76670', mapUrl: 'https://maps.google.com/?q=200+E+Main+St+Milford+TX' },
        eventType: 'city_council', governingBody: 'Milford City Council',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['water', 'roads', 'safety'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-45', title: 'Oak Leaf Town Council — Regular Meeting',
        description: 'Discussion on residential development standards, noise ordinance, and community events planning.',
        date: '2026-02-19', startTime: '19:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Oak Leaf Town Hall', address: '400 FM 1387', city: 'Oak Leaf', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=400+FM+1387+Oak+Leaf+TX' },
        eventType: 'city_council', governingBody: 'Oak Leaf Town Council',
        rsvpCount: 3, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Wednesday',
        tags: ['development', 'ordinance', 'community'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-46', title: 'Pecan Hill City Council — Regular Meeting',
        description: 'Items include road maintenance contracts, code enforcement updates, and budget review.',
        date: '2026-02-17', startTime: '18:30', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Pecan Hill City Hall', address: '200 Main St', city: 'Pecan Hill', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=Pecan+Hill+TX' },
        eventType: 'city_council', governingBody: 'Pecan Hill City Council',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['roads', 'code-enforcement', 'budget'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-47', title: 'Garrett City Council — Regular Meeting',
        description: 'Regular session covering utility services, road repairs, and community development.',
        date: '2026-02-20', startTime: '18:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Garrett City Hall', address: '100 N Main St', city: 'Garrett', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=Garrett+TX' },
        eventType: 'city_council', governingBody: 'Garrett City Council',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Friday',
        tags: ['utilities', 'roads', 'development'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-48', title: 'Bardwell City Council — Regular Meeting',
        description: 'Agenda includes lake recreation area management, public safety, and infrastructure maintenance.',
        date: '2026-02-18', startTime: '18:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Bardwell City Hall', address: '100 S Main St', city: 'Bardwell', state: 'TX', zip: '75101', mapUrl: 'https://maps.google.com/?q=Bardwell+TX' },
        eventType: 'city_council', governingBody: 'Bardwell City Council',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Wednesday',
        tags: ['lake', 'safety', 'infrastructure'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },

    // ─── School Board Meetings ───────────────────────────────
    {
        id: 'ce-11', title: 'Waxahachie ISD Board — Regular Meeting',
        description: 'Board meeting: teacher hiring update, bond proposal for new elementary school, and STAAR score analysis.',
        date: '2026-02-16', startTime: '18:30', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'WISD Administration Building', address: '411 N Gibson St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=411+N+Gibson+St+Waxahachie+TX' },
        eventType: 'school_board', governingBody: 'Waxahachie ISD Board of Trustees',
        agendaUrl: 'https://www.wisd.org/Page/BoardAgendas', zoomUrl: 'https://zoom.us/j/wisd-board',
        participationInstructions: 'Public comment period at 6:30 PM. Register online by noon on meeting day or in person. Each speaker gets 3 minutes.',
        rsvpCount: 22, rsvpUsers: [], isFeatured: true, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['teachers', 'bond', 'staar-scores'], sourceUrl: 'https://www.wisd.org', sourceName: 'Waxahachie ISD',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-12', title: 'Midlothian ISD Board — Regular Meeting',
        description: 'Agenda includes CTE program expansion, facilities assessment, and student enrollment projections for 2026-27.',
        date: '2026-02-19', startTime: '18:00', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'MISD Administration Building', address: '100 Walter Stephenson Rd', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=100+Walter+Stephenson+Rd+Midlothian+TX' },
        eventType: 'school_board', governingBody: 'Midlothian ISD Board of Trustees',
        agendaUrl: 'https://www.misd.gs/BoardAgendas',
        participationInstructions: 'Open public comment. Sign up in the lobby before 6:00 PM.',
        rsvpCount: 16, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['cte', 'facilities', 'enrollment'], sourceUrl: 'https://www.misd.gs', sourceName: 'Midlothian ISD',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-13', title: 'Red Oak ISD Board — Regular Meeting',
        description: 'Topics include athletic facility improvements, teacher retention incentives, and budget amendments.',
        date: '2026-02-17', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'ROISD Administration Building', address: '3108 S Houston School Rd', city: 'Red Oak', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=3108+S+Houston+School+Rd+Red+Oak+TX' },
        eventType: 'school_board', governingBody: 'Red Oak ISD Board of Trustees',
        rsvpCount: 11, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['athletics', 'teacher-retention', 'budget'], sourceUrl: 'https://www.redoakisd.org', sourceName: 'Red Oak ISD',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-14', title: 'Ennis ISD Board — Regular Meeting',
        description: 'Board agenda: dual-language program update, maintenance bond reauthorization, and food service contract.',
        date: '2026-02-20', startTime: '18:30', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Ennis ISD Administration', address: '303 W Knox St', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=303+W+Knox+St+Ennis+TX' },
        eventType: 'school_board', governingBody: 'Ennis ISD Board of Trustees',
        rsvpCount: 8, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['dual-language', 'maintenance', 'food-service'], sourceUrl: 'https://www.ennisisd.org', sourceName: 'Ennis ISD',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-15', title: 'Ferris ISD Board — Regular Meeting',
        description: 'Discussion on school security upgrades, staff compensation study, and technology refresh.',
        date: '2026-02-18', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Ferris ISD Admin', address: '216 E 8th St', city: 'Ferris', state: 'TX', zip: '75125' },
        eventType: 'school_board', governingBody: 'Ferris ISD Board of Trustees',
        rsvpCount: 5, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Wednesday',
        tags: ['security', 'compensation', 'technology'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-49', title: 'Palmer ISD Board — Regular Meeting',
        description: 'Topics include student achievement goals, transportation routing, and facility maintenance priorities.',
        date: '2026-02-19', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Palmer ISD Admin', address: '312 Shelton St', city: 'Palmer', state: 'TX', zip: '75152' },
        eventType: 'school_board', governingBody: 'Palmer ISD Board of Trustees',
        rsvpCount: 3, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['achievement', 'transportation', 'facilities'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-50', title: 'Italy ISD Board — Regular Meeting',
        description: 'Board meeting covering budget review, athletic program updates, and campus safety plans.',
        date: '2026-02-16', startTime: '18:00', endTime: '19:30', timezone: 'America/Chicago',
        location: { name: 'Italy ISD Admin', address: '100 Gladiator Way', city: 'Italy', state: 'TX', zip: '76651' },
        eventType: 'school_board', governingBody: 'Italy ISD Board of Trustees',
        rsvpCount: 3, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['budget', 'athletics', 'safety'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-51', title: 'Milford ISD Board — Regular Meeting',
        description: 'Agenda includes enrollment trends, staffing plans, and collaborative programs with neighboring districts.',
        date: '2026-02-17', startTime: '18:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Milford ISD', address: '200 W Main St', city: 'Milford', state: 'TX', zip: '76670' },
        eventType: 'school_board', governingBody: 'Milford ISD Board of Trustees',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Monday',
        tags: ['enrollment', 'staffing', 'collaboration'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-52', title: 'Maypearl ISD Board — Regular Meeting',
        description: 'Discussion of academic programs, extracurricular funding, and building maintenance.',
        date: '2026-02-18', startTime: '18:30', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Maypearl ISD Admin', address: '602 Main St', city: 'Maypearl', state: 'TX', zip: '76064' },
        eventType: 'school_board', governingBody: 'Maypearl ISD Board of Trustees',
        rsvpCount: 4, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Wednesday',
        tags: ['academics', 'extracurricular', 'maintenance'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-53', title: 'Avalon ISD Board — Regular Meeting',
        description: 'Board session covering student performance data, budget adjustments, and community partnerships.',
        date: '2026-02-19', startTime: '18:00', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Avalon ISD', address: '400 School St', city: 'Avalon', state: 'TX', zip: '76623' },
        eventType: 'school_board', governingBody: 'Avalon ISD Board of Trustees',
        rsvpCount: 2, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['performance', 'budget', 'partnerships'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },
    {
        id: 'ce-54', title: 'Venus ISD Board — Regular Meeting',
        description: 'Topics include new campus construction updates, teacher recruitment, and extracurricular program review.',
        date: '2026-02-20', startTime: '18:30', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Venus ISD Admin', address: '120 N Main St', city: 'Venus', state: 'TX', zip: '76084' },
        eventType: 'school_board', governingBody: 'Venus ISD Board of Trustees',
        rsvpCount: 4, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Friday',
        tags: ['construction', 'recruitment', 'extracurricular'], isUserSubmitted: false, approvalStatus: 'approved',
        lastVerified: '2026-02-08T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-07T14:00:00Z',
    },

    // ─── Planning & Zoning / Economic Dev ────────────────────
    {
        id: 'ce-16', title: 'Waxahachie Planning & Zoning Commission',
        description: 'Public hearing on proposed mixed-use development at US-77/I-35E interchange, residential subdivision plats, and sign ordinance amendments.',
        date: '2026-02-13', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie City Hall', address: '401 S Rogers St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=401+S+Rogers+St+Waxahachie+TX' },
        eventType: 'planning_zoning', governingBody: 'Waxahachie P&Z Commission',
        agendaUrl: 'https://www.waxahachie.com/PlanningZoning',
        participationInstructions: 'This is a public hearing. All affected property owners and interested citizens may speak on agenda items.',
        publicCommentDeadline: '2026-02-13T16:00:00Z',
        rsvpCount: 15, rsvpUsers: [], isFeatured: true, isRecurring: true, recurringSchedule: '2nd Thursday',
        tags: ['mixed-use', 'development', 'zoning'], sourceUrl: 'https://www.waxahachie.com', sourceName: 'City of Waxahachie',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-17', title: 'Midlothian Economic Development Corporation — Quarterly Meeting',
        description: 'Quarterly report on business attraction, retention efforts, and incentive agreements. Presentation on broadband expansion initiative.',
        date: '2026-02-25', startTime: '17:30', endTime: '19:00', timezone: 'America/Chicago',
        location: { name: 'Midlothian Conference Center', address: '1 Community Circle Dr', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=1+Community+Circle+Dr+Midlothian+TX' },
        eventType: 'economic_dev', governingBody: 'Midlothian EDC',
        participationInstructions: 'Open to the public. Q&A session after presentations.',
        rsvpCount: 10, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: 'Quarterly',
        tags: ['business', 'broadband', 'incentives'], sourceUrl: 'https://www.midlothian.tx.us', sourceName: 'City of Midlothian',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },

    // ─── Political Events ────────────────────────────────────
    {
        id: 'ce-18', title: 'Ellis County Republican Party — Monthly Meeting',
        description: 'Monthly meeting featuring candidate introductions for upcoming city council races and primary election preparation.',
        date: '2026-02-13', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Civic Center', address: '2200 Civic Center Ln', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=2200+Civic+Center+Ln+Waxahachie+TX' },
        eventType: 'party_meeting', governingBody: 'Ellis County Republican Party',
        participationInstructions: 'Open to all registered Republicans. Membership not required to attend.',
        rsvpCount: 35, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '2nd Thursday',
        tags: ['republican', 'primary', 'candidates'], sourceUrl: 'https://www.elliscountygop.org', sourceName: 'Ellis County Republican Party',
        lastVerified: '2026-02-08T18:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-19', title: 'Ellis County Democratic Party — Monthly Meeting',
        description: 'Monthly meeting with voter mobilization strategy, precinct captain training, and guest speaker on education policy.',
        date: '2026-02-20', startTime: '19:00', endTime: '21:00', timezone: 'America/Chicago',
        location: { name: 'Ennis Public Library', address: '501 W Ennis Ave', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=501+W+Ennis+Ave+Ennis+TX' },
        eventType: 'party_meeting', governingBody: 'Ellis County Democratic Party',
        participationInstructions: 'Open to all Democrats and interested community members.',
        rsvpCount: 22, rsvpUsers: [], isFeatured: false, isRecurring: true, recurringSchedule: '3rd Thursday',
        tags: ['democrat', 'voter-mobilization', 'education'], sourceUrl: 'https://www.elliscountydemocrats.org', sourceName: 'Ellis County Democratic Party',
        lastVerified: '2026-02-08T18:00:00Z', createdAt: '2026-01-20T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-20', title: 'Candidate Forum — Waxahachie City Council District 3',
        description: 'Moderated candidate forum for the District 3 city council race. Three candidates will present their platforms and answer questions from voters.',
        date: '2026-02-27', startTime: '18:30', endTime: '20:30', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Civic Center', address: '2200 Civic Center Ln', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=2200+Civic+Center+Ln+Waxahachie+TX' },
        eventType: 'candidate_forum', governingBody: 'Pivotal Voice / League of Women Voters',
        participationInstructions: 'Submit questions in advance at pivotalvoice.com or write them on cards at the event. Doors open at 6:00 PM.',
        rsvpCount: 45, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['city-council', 'candidate-forum', 'waxahachie'], sourceUrl: 'https://pivotalvoice.com/events', sourceName: 'Pivotal Voice',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-21', title: 'Meet & Greet — State Rep. District 10 Candidates',
        description: 'Informal meet and greet with candidates running for Texas State Representative District 10. Light refreshments provided.',
        date: '2026-02-22', startTime: '14:00', endTime: '16:00', timezone: 'America/Chicago',
        location: { name: 'Midlothian Community Park Pavilion', address: '4000 Community Center Dr', city: 'Midlothian', state: 'TX', zip: '76065', mapUrl: 'https://maps.google.com/?q=4000+Community+Center+Dr+Midlothian+TX' },
        eventType: 'meet_greet',
        participationInstructions: 'Open to all community members. Family-friendly event.',
        rsvpCount: 28, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['state-rep', 'meet-greet', 'midlothian'], sourceUrl: 'https://www.elliscountygop.org', sourceName: 'Ellis County Republican Party',
        lastVerified: '2026-02-08T18:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-22', title: 'Town Hall — Property Tax Reform',
        description: 'Town hall hosted by County Commissioner Precinct 2 on property tax reform proposals. Public Q&A session included.',
        date: '2026-02-26', startTime: '18:00', endTime: '20:00', timezone: 'America/Chicago',
        location: { name: 'Red Oak Community Center', address: '100 Community Dr', city: 'Red Oak', state: 'TX', zip: '75154', mapUrl: 'https://maps.google.com/?q=Red+Oak+Community+Center+TX' },
        eventType: 'town_hall', governingBody: 'Ellis County Commissioner Precinct 2',
        zoomUrl: 'https://zoom.us/j/property-tax-townhall',
        participationInstructions: 'In-person and virtual attendance options. Submit questions online or ask during the Q&A period.',
        rsvpCount: 38, rsvpUsers: [], isFeatured: true, isRecurring: false,
        tags: ['property-tax', 'town-hall', 'red-oak'], sourceUrl: 'https://www.co.ellis.tx.us', sourceName: 'Ellis County Official Website',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-23', title: 'Voter Registration Drive — Ennis',
        description: 'Free voter registration and education event. Bilingual registration assistance available. Bring your Texas ID or last 4 of SSN.',
        date: '2026-02-15', startTime: '10:00', endTime: '14:00', timezone: 'America/Chicago',
        location: { name: 'Ennis Public Library', address: '501 W Ennis Ave', city: 'Ennis', state: 'TX', zip: '75119', mapUrl: 'https://maps.google.com/?q=501+W+Ennis+Ave+Ennis+TX' },
        eventType: 'voter_registration',
        participationInstructions: 'No appointment needed. Bring a valid Texas driver\'s license or ID, or the last 4 digits of your SSN. Bilingual staff available.',
        rsvpCount: 15, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['voter-registration', 'bilingual', 'ennis'], sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
    {
        id: 'ce-24', title: 'Voter Registration Drive — Waxahachie',
        description: 'Community voter registration event at the farmers market. Register, check your status, or update your address.',
        date: '2026-02-22', startTime: '08:00', endTime: '12:00', timezone: 'America/Chicago',
        location: { name: 'Waxahachie Downtown Farmers Market', address: '400 S Rogers St', city: 'Waxahachie', state: 'TX', zip: '75165', mapUrl: 'https://maps.google.com/?q=400+S+Rogers+St+Waxahachie+TX' },
        eventType: 'voter_registration',
        participationInstructions: 'Stop by the registration booth anytime. Volunteers will assist you with the process.',
        rsvpCount: 8, rsvpUsers: [], isFeatured: false, isRecurring: false,
        tags: ['voter-registration', 'farmers-market', 'waxahachie'], sourceUrl: 'https://www.sos.texas.gov/elections', sourceName: 'Texas Secretary of State',
        lastVerified: '2026-02-09T06:00:00Z', createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-02-08T14:00:00Z',
        isUserSubmitted: false, approvalStatus: 'approved',
    },
];
