---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/pivotal-voice
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .env.local.example $DEPLOYPATH/ 2>/dev/null; true
    - source /home/$USER/nodevenv/pivotal-voice/24/bin/activate && cd $DEPLOYPATH && npm install
