import { ForumCategory, Topic, Reply, ForumUser, LocalResource } from '@/lib/types/forum';

// ─── Categories ────────────────────────────────────────────
export const FORUM_CATEGORIES: ForumCategory[] = [
    { id: 'infrastructure', name: 'Infrastructure & Transportation', description: 'Roads, I-35E, public transit, and DFW expansion impacts', icon: 'truck', topicCount: 0, color: 'blue', order: 1 },
    { id: 'growth', name: 'Growth & Development', description: 'Residential growth, water capacity, affordable housing, and rural preservation', icon: 'building', topicCount: 0, color: 'green', order: 2 },
    { id: 'taxes', name: 'Property Taxes & Budget', description: 'Tax appraisals, school bonds, county spending transparency', icon: 'dollar', topicCount: 0, color: 'gold', order: 3 },
    { id: 'education', name: 'Education', description: 'School overcrowding, teacher pay, safety, CTE programs', icon: 'book', topicCount: 0, color: 'purple', order: 4 },
    { id: 'safety', name: 'Public Safety', description: 'Emergency response, I-35 crime, VFD funding, mental health crisis', icon: 'shield', topicCount: 0, color: 'red', order: 5 },
    { id: 'economic', name: 'Economic Development', description: 'Business diversity, broadband, workforce development', icon: 'briefcase', topicCount: 0, color: 'teal', order: 6 },
    { id: 'agriculture', name: 'Agriculture & Rural Life', description: 'Ag exemptions, drought, urban sprawl, livestock regulations', icon: 'leaf', topicCount: 0, color: 'emerald', order: 7 },
    { id: 'healthcare', name: 'Healthcare', description: 'Hospital access, mental health, senior care, EMS coverage', icon: 'heart', topicCount: 0, color: 'pink', order: 8 },
    { id: 'quality', name: 'Quality of Life', description: 'Parks, libraries, youth programs, historic preservation', icon: 'sun', topicCount: 0, color: 'orange', order: 9 },
    { id: 'environment', name: 'Environment & Utilities', description: 'Groundwater, waste management, flood control, power grid', icon: 'droplet', topicCount: 0, color: 'cyan', order: 10 },
];

// ─── Seed Users ────────────────────────────────────────────
export const SEED_USERS: ForumUser[] = [
    { id: 'user-admin', email: 'admin@pivotalvoice.com', displayName: 'PV Admin', passwordHash: '', joinDate: '2025-06-01T00:00:00Z', city: 'Waxahachie', reputation: 500, topicCount: 5, replyCount: 30, isAdmin: true, isModerator: true, followedTopics: [], notifications: [], bio: 'Pivotal Voice platform administrator' },
    { id: 'user-001', email: 'marcus.w@email.com', displayName: 'MarcusW', passwordHash: '', joinDate: '2025-08-15T00:00:00Z', city: 'Waxahachie', isBusinessOwner: true, yearsInCounty: 22, reputation: 145, topicCount: 8, replyCount: 45, followedTopics: [], notifications: [], bio: 'Small business owner, downtown Waxahachie' },
    { id: 'user-002', email: 'sarah.m@email.com', displayName: 'SarahMidlothian', passwordHash: '', joinDate: '2025-09-01T00:00:00Z', city: 'Midlothian', yearsInCounty: 7, reputation: 98, topicCount: 5, replyCount: 32, followedTopics: [], notifications: [], bio: 'Mom of 3, involved in Midlothian ISD PTA' },
    { id: 'user-003', email: 'javier.g@email.com', displayName: 'JavierG_Ennis', passwordHash: '', joinDate: '2025-09-20T00:00:00Z', city: 'Ennis', isBusinessOwner: true, yearsInCounty: 15, reputation: 112, topicCount: 6, replyCount: 28, followedTopics: [], notifications: [], bio: 'Ennis restaurant owner, volunteer firefighter' },
    { id: 'user-004', email: 'betty.r@email.com', displayName: 'BettyRancher', passwordHash: '', joinDate: '2025-10-05T00:00:00Z', city: 'Italy', yearsInCounty: 40, reputation: 87, topicCount: 4, replyCount: 22, followedTopics: [], notifications: [], bio: 'Third-generation cattle rancher near Italy' },
    { id: 'user-005', email: 'devon.t@email.com', displayName: 'DevonTeacher', passwordHash: '', joinDate: '2025-10-15T00:00:00Z', city: 'Red Oak', yearsInCounty: 5, reputation: 76, topicCount: 3, replyCount: 18, followedTopics: [], notifications: [], bio: 'High school teacher in ROISD' },
    { id: 'user-006', email: 'tom.h@email.com', displayName: 'TomH_Palmer', passwordHash: '', joinDate: '2025-11-01T00:00:00Z', city: 'Palmer', yearsInCounty: 12, reputation: 64, topicCount: 3, replyCount: 15, followedTopics: [], notifications: [], bio: 'Palmer city council watcher' },
    { id: 'user-007', email: 'nina.k@email.com', displayName: 'NinaK_RN', passwordHash: '', joinDate: '2025-11-10T00:00:00Z', city: 'Midlothian', yearsInCounty: 3, reputation: 55, topicCount: 2, replyCount: 20, followedTopics: [], notifications: [], bio: 'ER nurse, healthcare access advocate' },
    { id: 'user-008', email: 'carlos.p@email.com', displayName: 'CarlosP', passwordHash: '', joinDate: '2025-12-01T00:00:00Z', city: 'Waxahachie', yearsInCounty: 8, reputation: 42, topicCount: 2, replyCount: 12, followedTopics: [], notifications: [], bio: 'IT professional, work from home' },
];

// ─── Seed Topics ────────────────────────────────────────────
const now = new Date();
const h = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
const d = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const SEED_TOPICS: Topic[] = [
    // Infrastructure & Transportation
    { id: 'topic-001', title: 'I-35E congestion is getting dangerous — what can we do?', body: 'I commute from Waxahachie to Dallas daily and the I-35E corridor has become a nightmare. Multiple accidents every week, no viable alternate routes, and the construction seems never-ending. Other counties have successfully lobbied TxDOT for express lanes and improved on/off ramps. What would it take to get Ellis County organized around this? Has anyone attended the TxDOT public meetings?', categoryId: 'infrastructure', authorId: 'user-001', authorName: 'MarcusW', createdAt: h(3), updatedAt: h(3), upvotes: 47, downvotes: 2, replyCount: 12, viewCount: 234, isPinned: true, isLocked: false, isAnonymous: false, tags: ['I-35E', 'commute', 'TxDOT', 'safety'], lastReplyAt: h(0.5), lastReplyBy: 'CarlosP', voters: {} },
    { id: 'topic-002', title: 'FM 664 potholes — anyone reported these to the county?', body: 'The stretch of FM 664 between Midlothian and Red Oak is in terrible shape. I counted 15+ potholes just on my drive to work this morning. My neighbor busted a tire last week. Has anyone successfully reported these and gotten a response from the county maintenance department? What\'s the best way to get action?', categoryId: 'infrastructure', authorId: 'user-002', authorName: 'SarahMidlothian', createdAt: h(8), updatedAt: h(8), upvotes: 31, downvotes: 0, replyCount: 8, viewCount: 156, isPinned: false, isLocked: false, isAnonymous: false, tags: ['roads', 'maintenance', 'FM-664'], lastReplyAt: h(2), lastReplyBy: 'TomH_Palmer', voters: {} },
    { id: 'topic-003', title: 'Public transportation — will Ellis County ever get a bus or rail option?', body: 'With all the growth happening, a lot of residents can\'t afford to drive or maintain a vehicle. Senior citizens in particular are stranded. Even a basic shuttle service connecting Waxahachie, Midlothian, and Red Oak to the DART stations would be huge. Has Commissioners Court ever discussed this?', categoryId: 'infrastructure', authorId: 'user-008', authorName: 'CarlosP', createdAt: d(2), updatedAt: d(2), upvotes: 22, downvotes: 5, replyCount: 6, viewCount: 98, isPinned: false, isLocked: false, isAnonymous: false, tags: ['public-transit', 'DART', 'seniors'], voters: {} },

    // Growth & Development
    { id: 'topic-004', title: 'Another 500-home subdivision approved near Midlothian — where will the water come from?', body: 'Commissioners just approved another massive residential development off FM 663. That\'s the third one this year. Meanwhile, we had water restrictions last summer and our water treatment plant is already at 85% capacity. The developers get their profits and leave us dealing with the infrastructure burden. When will our county leaders start requiring developers to fund water infrastructure upgrades?', categoryId: 'growth', authorId: 'user-002', authorName: 'SarahMidlothian', createdAt: h(5), updatedAt: h(5), upvotes: 56, downvotes: 3, replyCount: 15, viewCount: 312, isPinned: false, isLocked: false, isAnonymous: false, tags: ['development', 'water', 'Midlothian', 'growth'], lastReplyAt: h(1), lastReplyBy: 'MarcusW', voters: {} },
    { id: 'topic-005', title: 'Preserving Ellis County\'s rural character — are we too late?', body: 'I moved to Ellis County 20 years ago specifically for the rural atmosphere, the open spaces, the small-town feel. Now I see strip malls going up on every corner, cookie-cutter subdivisions replacing farmland, and chain restaurants pushing out local businesses. Is there any organized effort to preserve what makes this county special? Other Texas counties have implemented conservation easements and smart growth policies.', categoryId: 'growth', authorId: 'user-004', authorName: 'BettyRancher', createdAt: d(1), updatedAt: d(1), upvotes: 43, downvotes: 8, replyCount: 11, viewCount: 245, isPinned: false, isLocked: false, isAnonymous: false, tags: ['rural', 'preservation', 'smart-growth'], lastReplyAt: h(6), lastReplyBy: 'JavierG_Ennis', voters: {} },
    { id: 'topic-006', title: 'Affordable housing in Ellis County — priced out of our own community', body: 'Average home prices in Ellis County jumped 35% in the last 3 years. Rent has followed. Teachers, first responders, and service workers who grew up here can\'t afford to stay. My daughter is a nurse at Baylor Scott & White and she\'s looking at commuting from Corsicana because she can\'t find anything affordable here. What solutions have other communities tried?', categoryId: 'growth', authorId: 'user-007', authorName: 'NinaK_RN', createdAt: d(3), updatedAt: d(3), upvotes: 38, downvotes: 4, replyCount: 9, viewCount: 189, isPinned: false, isLocked: false, isAnonymous: false, tags: ['housing', 'affordability', 'cost-of-living'], voters: {} },

    // Property Taxes & Budget
    { id: 'topic-007', title: 'Property tax appraisal went up 28% — how do I protest effectively?', body: 'Just got my appraisal notice and my property value jumped from $285,000 to $365,000. That\'s a 28% increase! Nothing about my house has changed. I know I can protest but I\'ve never done it before. Has anyone successfully protested their appraisal in Ellis County? What evidence do I need? Is it worth hiring one of those protest companies?', categoryId: 'taxes', authorId: 'user-008', authorName: 'CarlosP', createdAt: h(4), updatedAt: h(4), upvotes: 52, downvotes: 1, replyCount: 14, viewCount: 287, isPinned: true, isLocked: false, isAnonymous: false, tags: ['property-tax', 'appraisal', 'protest'], lastReplyAt: h(1.5), lastReplyBy: 'BettyRancher', voters: {} },
    { id: 'topic-008', title: 'WISD bond proposal — $180M for new school facilities', body: 'Waxahachie ISD just announced their upcoming bond election for $180 million. They say it\'s needed for a new middle school, elementary expansion, and athletic facilities. I support education but that\'s a huge amount. Has anyone seen the detailed breakdown? How much would this actually add to our tax bills? The district website has some info but I want to hear from other parents and taxpayers.', categoryId: 'taxes', authorId: 'user-001', authorName: 'MarcusW', createdAt: d(2), updatedAt: d(2), upvotes: 34, downvotes: 6, replyCount: 18, viewCount: 342, isPinned: false, isLocked: false, isAnonymous: false, tags: ['school-bond', 'WISD', 'education-funding'], lastReplyAt: h(4), lastReplyBy: 'DevonTeacher', voters: {} },
    { id: 'topic-009', title: 'County budget meeting recap — where is our money going?', body: 'I attended the Commissioners Court budget hearing last Tuesday. Here\'s my summary: Law enforcement got a 12% increase, road maintenance got 8%, but parks and libraries only got 2%. The county judge mentioned a potential new county building downtown. Meanwhile, the volunteer fire departments are begging for equipment. I\'ll share my notes — what are your priorities for the county budget?', categoryId: 'taxes', authorId: 'user-006', authorName: 'TomH_Palmer', createdAt: d(4), updatedAt: d(4), upvotes: 29, downvotes: 2, replyCount: 7, viewCount: 145, isPinned: false, isLocked: false, isAnonymous: false, tags: ['county-budget', 'commissioners-court', 'spending'], voters: {} },

    // Education
    { id: 'topic-010', title: 'Midlothian ISD overcrowding — portable buildings are not the answer', body: 'My kid\'s school now has 8 portable buildings. The cafeteria can\'t seat all students so they have 4 lunch periods starting at 10:30 AM. Class sizes are pushing 30. When Midlothian ISD approved all these new developments, where was the plan for school capacity? This affects the quality of education our kids receive. Is a bond election coming?', categoryId: 'education', authorId: 'user-002', authorName: 'SarahMidlothian', createdAt: h(6), updatedAt: h(6), upvotes: 41, downvotes: 1, replyCount: 13, viewCount: 267, isPinned: false, isLocked: false, isAnonymous: false, tags: ['MISD', 'overcrowding', 'school-capacity'], lastReplyAt: h(2), lastReplyBy: 'DevonTeacher', voters: {} },
    { id: 'topic-011', title: 'Teacher shortage is real — my perspective from inside the classroom', body: 'I\'ve been teaching in ROISD for 5 years and I can tell you, we\'re hemorrhaging teachers. Low pay compared to DFW districts, increasing class sizes, and the lack of respect from administration is driving people out. Three teachers in my department alone quit mid-year. Substitutes are impossible to find. Parents, you should know what\'s really happening in our schools.', categoryId: 'education', authorId: 'user-005', authorName: 'DevonTeacher', createdAt: d(1), updatedAt: d(1), upvotes: 67, downvotes: 3, replyCount: 22, viewCount: 456, isPinned: false, isLocked: false, isAnonymous: false, tags: ['teachers', 'ROISD', 'pay', 'retention'], lastReplyAt: h(3), lastReplyBy: 'SarahMidlothian', voters: {} },
    { id: 'topic-012', title: 'Career tech programs — are we preparing kids for real jobs?', body: 'Not every kid is going to college, and that\'s okay. But are our school districts offering enough CTE programs? The construction, welding, healthcare, and IT industries are desperate for workers. I\'d love to see more partnerships between our high schools and local employers. What CTE programs do your kids\' schools offer?', categoryId: 'education', authorId: 'user-003', authorName: 'JavierG_Ennis', createdAt: d(5), updatedAt: d(5), upvotes: 25, downvotes: 2, replyCount: 6, viewCount: 112, isPinned: false, isLocked: false, isAnonymous: false, tags: ['CTE', 'workforce', 'career-readiness'], voters: {} },

    // Public Safety
    { id: 'topic-013', title: 'Rural response times — 20+ minutes for an ambulance is unacceptable', body: 'My father-in-law had a heart attack on his property near Avalon last month. It took 23 minutes for the ambulance to arrive. In cardiac emergencies, every minute matters. This isn\'t a criticism of our EMS workers — they\'re stretched thin. But our county needs to fund additional EMS stations in underserved rural areas. How many people have to die before this becomes a priority?', categoryId: 'safety', authorId: 'user-004', authorName: 'BettyRancher', createdAt: h(10), updatedAt: h(10), upvotes: 58, downvotes: 0, replyCount: 16, viewCount: 378, isPinned: false, isLocked: false, isAnonymous: false, tags: ['EMS', 'rural', 'response-time', 'emergency'], lastReplyAt: h(2), lastReplyBy: 'NinaK_RN', voters: {} },
    { id: 'topic-014', title: 'VFD needs your help — Volunteer Fire Dept fundraiser this Saturday', body: 'The Palmer Volunteer Fire Department is holding their annual BBQ fundraiser this Saturday at the community center. These folks protect our homes and families on a shoestring budget. Last year they responded to 340 calls with equipment that\'s 15+ years old. Come out, buy some BBQ, and support the people who show up when you call 911. Details in the post.', categoryId: 'safety', authorId: 'user-006', authorName: 'TomH_Palmer', createdAt: d(1), updatedAt: d(1), upvotes: 35, downvotes: 0, replyCount: 5, viewCount: 167, isPinned: false, isLocked: false, isAnonymous: false, tags: ['VFD', 'Palmer', 'fundraiser', 'community'], voters: {} },
    { id: 'topic-015', title: 'Mental health crisis in Ellis County — we need better resources', body: 'After recent events in our community, it\'s clear we lack adequate mental health crisis intervention. The sheriff\'s office is often the only responder for mental health calls, and they\'re not trained counselors. Does anyone know what crisis resources are actually available in Ellis County? I know MHMR of Tarrant County technically covers our area but the waits are months long.', categoryId: 'safety', authorId: 'user-007', authorName: 'NinaK_RN', createdAt: d(3), updatedAt: d(3), upvotes: 44, downvotes: 1, replyCount: 10, viewCount: 223, isPinned: false, isLocked: false, isAnonymous: false, tags: ['mental-health', 'crisis', 'resources'], voters: {} },

    // Economic Development
    { id: 'topic-016', title: 'Attracting businesses beyond bedrooms — Ellis County needs economic diversity', body: 'Ellis County is rapidly becoming a bedroom community for DFW. Most of us drive 45+ minutes to work in Dallas. That means our retail sales tax revenue is going to other counties while we shoulder infrastructure costs. What would it take to attract employers HERE? Other fast-growing TX counties have created business incentive packages. Are our county leaders working on this?', categoryId: 'economic', authorId: 'user-001', authorName: 'MarcusW', createdAt: d(2), updatedAt: d(2), upvotes: 33, downvotes: 4, replyCount: 9, viewCount: 178, isPinned: false, isLocked: false, isAnonymous: false, tags: ['economic-development', 'jobs', 'commuting'], voters: {} },
    { id: 'topic-017', title: 'Broadband internet in rural Ellis County — still on DSL in 2026', body: 'I live 8 miles outside of Ennis and my only internet option is 5 Mbps DSL. I can\'t work from home, my kids can\'t do homework reliably, and I can\'t stream anything. Meanwhile, new subdivisions a mile away get fiber. This is a basic infrastructure issue that affects property values, education, and economic opportunity. Who\'s responsible for getting broadband to rural areas?', categoryId: 'economic', authorId: 'user-003', authorName: 'JavierG_Ennis', createdAt: d(4), updatedAt: d(4), upvotes: 40, downvotes: 1, replyCount: 11, viewCount: 201, isPinned: false, isLocked: false, isAnonymous: false, tags: ['broadband', 'rural', 'internet', 'infrastructure'], voters: {} },

    // Agriculture
    { id: 'topic-018', title: 'Ag exemption changes — what Texas HB proposed changes mean for landowners', body: 'There\'s talk in Austin about modifying agricultural exemption requirements. For those of us who depend on ag exemptions to keep our land viable, this is terrifying. Some proposals would increase minimum acreage and require proof of agricultural income. Has anyone read the actual proposed legislation? I want to understand what we\'re up against before it\'s too late to act.', categoryId: 'agriculture', authorId: 'user-004', authorName: 'BettyRancher', createdAt: h(12), updatedAt: h(12), upvotes: 37, downvotes: 5, replyCount: 8, viewCount: 189, isPinned: false, isLocked: false, isAnonymous: false, tags: ['ag-exemption', 'property-tax', 'legislation'], lastReplyAt: h(4), lastReplyBy: 'TomH_Palmer', voters: {} },
    { id: 'topic-019', title: 'Urban sprawl pushing farms out — a firsthand account', body: 'My family has farmed 200 acres south of Waxahachie for three generations. In the last 5 years, we\'ve had subdivisions built on three sides. Now we get complaints about tractor noise at 6 AM, dust from harvesting, and the smell of cattle. The developers knew this was agricultural land when they built. Texas has Right to Farm laws but the pressure to sell is immense when your property is appraised at residential rates.', categoryId: 'agriculture', authorId: 'user-004', authorName: 'BettyRancher', createdAt: d(6), updatedAt: d(6), upvotes: 51, downvotes: 2, replyCount: 14, viewCount: 298, isPinned: false, isLocked: false, isAnonymous: false, tags: ['farming', 'urban-sprawl', 'right-to-farm'], voters: {} },

    // Healthcare
    { id: 'topic-020', title: 'Nearest specialist is 45 minutes away — healthcare access in Ellis County', body: 'When my daughter needed a pediatric neurologist, the closest one accepting patients was in Dallas. That\'s 45 minutes without traffic (so really an hour+). Dermatology, cardiology, endocrinology — all require a trip to DFW. For seniors who can\'t drive, this is a crisis. Has anyone heard about plans for more specialist clinics in Waxahachie or Midlothian?', categoryId: 'healthcare', authorId: 'user-007', authorName: 'NinaK_RN', createdAt: d(2), updatedAt: d(2), upvotes: 39, downvotes: 0, replyCount: 7, viewCount: 167, isPinned: false, isLocked: false, isAnonymous: false, tags: ['healthcare', 'specialists', 'access'], voters: {} },
    { id: 'topic-021', title: 'Senior care options in Ellis County — help needed', body: 'My mom is 82 and needs assisted living but wants to stay in Ellis County near family. The options here are extremely limited and expensive. Most families I know are driving their parents to facilities in Dallas or Hillsboro. Does anyone have experience with senior care options locally? Are there any new facilities planned?', categoryId: 'healthcare', authorId: 'user-006', authorName: 'TomH_Palmer', createdAt: d(5), updatedAt: d(5), upvotes: 28, downvotes: 0, replyCount: 6, viewCount: 134, isPinned: false, isLocked: false, isAnonymous: false, tags: ['senior-care', 'assisted-living', 'aging'], voters: {} },

    // Quality of Life
    { id: 'topic-022', title: 'Parks and trails master plan — Waxahachie needs more green space', body: 'Waxahachie\'s population has nearly doubled but we haven\'t added a single new park in 10 years. The Getzendaner trails are wonderful but always packed. Other growing cities prioritize park land during development approvals. Could we require developers to dedicate park space or contribute to a parks fund? Quality of life amenities attract families and businesses.', categoryId: 'quality', authorId: 'user-001', authorName: 'MarcusW', createdAt: d(3), updatedAt: d(3), upvotes: 36, downvotes: 2, replyCount: 8, viewCount: 154, isPinned: false, isLocked: false, isAnonymous: false, tags: ['parks', 'trails', 'green-space', 'Waxahachie'], voters: {} },
    { id: 'topic-023', title: 'Library hours cut again — when will our county invest in literacy?', body: 'The Nicholas P. Sims Library just announced reduced Saturday hours again. This is the third cut in two years. For working families, weeknight and weekend hours are the ONLY time we can bring our kids. Libraries aren\'t just about books — they\'re community centers offering programs, internet access, and resources for all ages. The county budget for libraries needs to be a priority.', categoryId: 'quality', authorId: 'user-005', authorName: 'DevonTeacher', createdAt: d(4), updatedAt: d(4), upvotes: 30, downvotes: 3, replyCount: 5, viewCount: 112, isPinned: false, isLocked: false, isAnonymous: false, tags: ['library', 'hours', 'funding', 'literacy'], voters: {} },
    { id: 'topic-024', title: 'Historic downtown Waxahachie — preserving what makes us unique', body: 'Our historic courthouse square is one of the most beautiful in Texas. But I\'ve noticed some property owners letting buildings deteriorate, and there\'s been talk of demolishing the old Masonic lodge for a parking lot. Ellis County\'s history IS our identity and a major tourism draw. What can we do to support historic preservation? Are there grants or tax incentives available?', categoryId: 'quality', authorId: 'user-003', authorName: 'JavierG_Ennis', createdAt: d(7), updatedAt: d(7), upvotes: 42, downvotes: 1, replyCount: 9, viewCount: 198, isPinned: false, isLocked: false, isAnonymous: false, tags: ['historic', 'preservation', 'downtown', 'tourism'], voters: {} },

    // Environment & Utilities
    { id: 'topic-025', title: 'Groundwater contamination concerns near old industrial sites', body: 'I recently learned about historical industrial contamination near the Superconducting Super Collider site and some older properties in Ennis. My well water hasn\'t been tested in years. Does anyone know how to get well water tested in Ellis County? Are there any known contamination plumes the county should be disclosing to residents?', categoryId: 'environment', authorId: 'user-003', authorName: 'JavierG_Ennis', createdAt: d(1), updatedAt: d(1), upvotes: 33, downvotes: 0, replyCount: 7, viewCount: 156, isPinned: false, isLocked: false, isAnonymous: false, tags: ['groundwater', 'contamination', 'well-water', 'SSC'], lastReplyAt: h(8), lastReplyBy: 'BettyRancher', voters: {} },
    { id: 'topic-026', title: 'Flooding on Waxahachie Creek — is anyone tracking this?', body: 'Every time we get heavy rain, the area along Waxahachie Creek floods. The roads near Farley and Brown St become impassable. I know FEMA has updated flood maps but it seems like development upstream has made things worse. Has the city done any drainage studies? Are there mitigation projects planned?', categoryId: 'environment', authorId: 'user-008', authorName: 'CarlosP', createdAt: d(3), updatedAt: d(3), upvotes: 26, downvotes: 1, replyCount: 5, viewCount: 98, isPinned: false, isLocked: false, isAnonymous: false, tags: ['flooding', 'drainage', 'Waxahachie-Creek'], voters: {} },
    { id: 'topic-027', title: 'Power grid reliability — what\'s Ellis County\'s plan for the next winter storm?', body: 'After the 2021 freeze and the continued strain on Texas\' power grid, I want to know what Ellis County has done to prepare. Are any of our critical facilities (hospitals, shelters, water treatment plants) on backup generators? Has the county established warming centers? What should we individually be doing to prepare? I don\'t want a repeat of 2021.', categoryId: 'environment', authorId: 'user-002', authorName: 'SarahMidlothian', createdAt: d(5), updatedAt: d(5), upvotes: 45, downvotes: 2, replyCount: 12, viewCount: 234, isPinned: false, isLocked: false, isAnonymous: false, tags: ['power-grid', 'winter-storm', 'preparedness'], voters: {} },
];

// ─── Seed Replies ────────────────────────────────────────────
export const SEED_REPLIES: Reply[] = [
    // Replies to I-35E topic
    { id: 'reply-001', topicId: 'topic-001', body: 'I attend TxDOT meetings regularly. They said I-35E expansion south of Waxahachie is "on the 10-year plan" which basically means not anytime soon. We need to push our state representative to fast-track this. Lives are literally at risk.', authorId: 'user-006', authorName: 'TomH_Palmer', createdAt: h(2.5), updatedAt: h(2.5), upvotes: 18, downvotes: 1, isAnonymous: false, voters: {} },
    { id: 'reply-002', topicId: 'topic-001', parentReplyId: 'reply-001', body: 'Thank you for going to those meetings Tom. Can you share when the next one is? I\'d like to bring some other business owners. The accidents on 35 between Waxahachie and Red Oak are costing me employees who refuse to make that commute.', authorId: 'user-001', authorName: 'MarcusW', createdAt: h(2), updatedAt: h(2), upvotes: 12, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-003', topicId: 'topic-001', body: 'Have you all looked into the 287 bypass option? I know it adds time but it\'s significantly safer. I switched my commute route 6 months ago and my stress levels dropped dramatically.', authorId: 'user-008', authorName: 'CarlosP', createdAt: h(0.5), updatedAt: h(0.5), upvotes: 8, downvotes: 3, isAnonymous: false, voters: {} },

    // Replies to water/development topic
    { id: 'reply-004', topicId: 'topic-004', body: 'I work in water infrastructure and I can tell you — Ellis County Water Authority is scrambling. The current treatment plant was built for 80,000 residents and we\'re approaching 200,000. A new treatment plant would cost $120M+ and take 5 years to build. The time to start was 10 years ago.', authorId: 'user-008', authorName: 'CarlosP', createdAt: h(4), updatedAt: h(4), upvotes: 34, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-005', topicId: 'topic-004', parentReplyId: 'reply-004', body: 'This is terrifying. Has anyone brought this up at Commissioners Court? If the treatment plant is at 85% capacity and we\'re approving thousands of new homes, we\'re heading for a crisis.', authorId: 'user-002', authorName: 'SarahMidlothian', createdAt: h(3), updatedAt: h(3), upvotes: 22, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-006', topicId: 'topic-004', body: 'Developer impact fees in Ellis County are among the lowest in the DFW area. Compare: Denton County charges $4,500 per lot for water impact, Ellis County charges $1,200. That difference has to come from somewhere — our tax bills.', authorId: 'user-001', authorName: 'MarcusW', createdAt: h(1), updatedAt: h(1), upvotes: 28, downvotes: 2, isAnonymous: false, voters: {} },

    // Replies to property tax topic
    { id: 'reply-007', topicId: 'topic-007', body: 'I protested last year and got a $25K reduction. Here\'s my tips: 1) Print comparable sales from Zillow/Redfin for similar homes, 2) Take photos of any issues with your property, 3) Check if the appraisal district has the correct square footage, 4) Be polite and stick to facts. The informal hearing is worth trying before going to ARB.', authorId: 'user-001', authorName: 'MarcusW', createdAt: h(3.5), updatedAt: h(3.5), upvotes: 42, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-008', topicId: 'topic-007', parentReplyId: 'reply-007', body: 'This is incredibly helpful! Did you do the informal hearing over the phone or in person? I\'m nervous about going in person.', authorId: 'user-008', authorName: 'CarlosP', createdAt: h(2.5), updatedAt: h(2.5), upvotes: 8, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-009', topicId: 'topic-007', parentReplyId: 'reply-008', body: 'I did mine by phone! They\'re very accommodating. You can also submit evidence online now through the ECCAD website. Much less intimidating than a formal hearing.', authorId: 'user-001', authorName: 'MarcusW', createdAt: h(2), updatedAt: h(2), upvotes: 15, downvotes: 0, isAnonymous: false, voters: {} },

    // Replies to teacher shortage topic
    { id: 'reply-010', topicId: 'topic-011', body: 'As a parent I see this every day. My son\'s math class has had 3 different teachers this year. The lack of continuity is destroying their learning. Devon, thank you for staying and fighting for our kids. What can parents do to support you?', authorId: 'user-002', authorName: 'SarahMidlothian', createdAt: h(12), updatedAt: h(12), upvotes: 35, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-011', topicId: 'topic-011', parentReplyId: 'reply-010', body: 'Honestly? Show up at school board meetings. Email the trustees. Let them know that competitive pay isn\'t optional — it\'s survival. Dallas ISD starts at $61K. ROISD starts at $52K. For the same job with the same requirements. Why would anyone choose us?', authorId: 'user-005', authorName: 'DevonTeacher', createdAt: h(10), updatedAt: h(10), upvotes: 29, downvotes: 1, isAnonymous: false, voters: {} },

    // Replies to rural EMS topic
    { id: 'reply-012', topicId: 'topic-013', body: 'As an ER nurse, I can tell you that response time directly correlates with survival rates for cardiac events. After 10 minutes without intervention, survival drops to less than 5%. Ellis County needs at minimum 2 additional EMS stations south of Ennis and east of Waxahachie. This should be the #1 budget priority.', authorId: 'user-007', authorName: 'NinaK_RN', createdAt: h(8), updatedAt: h(8), upvotes: 41, downvotes: 0, isAnonymous: false, voters: {} },
    { id: 'reply-013', topicId: 'topic-013', body: 'My VFD often responds to medical calls because we\'re closer than EMS. We\'re trained in basic first aid and can use an AED, but we\'re not paramedics. The county is basically relying on unpaid volunteers to cover gaps in emergency services. Something has to change.', authorId: 'user-003', authorName: 'JavierG_Ennis', createdAt: h(6), updatedAt: h(6), upvotes: 33, downvotes: 0, isAnonymous: false, voters: {} },
];

// ─── Local Resources ────────────────────────────────────────
export const LOCAL_RESOURCES: LocalResource[] = [
    { name: 'Ellis County Government', description: 'Official county website', url: 'https://www.co.ellis.tx.us', category: 'government' },
    { name: 'Ellis County Elections', description: 'Register, polling locations, results', url: 'https://www.co.ellis.tx.us/149/Elections', category: 'government' },
    { name: 'Commissioners Court Agendas', description: 'Meeting agendas and minutes', url: 'https://www.co.ellis.tx.us/agendacenter', category: 'government' },
    { name: 'Ellis County Appraisal District', description: 'Property values and protests', url: 'https://www.elliscad.com', category: 'government' },
    { name: 'Ellis County Sheriff', description: 'Non-emergency contact', url: 'https://www.co.ellis.tx.us/200/Sheriff', phone: '972-825-4901', category: 'emergency' },
    { name: 'Emergency: 911', description: 'Police, Fire, EMS emergencies', url: '#', phone: '911', category: 'emergency' },
    { name: 'Crisis Hotline — 988', description: 'Suicide & crisis lifeline', url: 'https://988lifeline.org', phone: '988', category: 'emergency' },
    { name: 'TxDOT — Report Road Issues', description: 'State road maintenance requests', url: 'https://www.txdot.gov', phone: '800-452-9292', category: 'services' },
    { name: 'Texas Voter Registration', description: 'Check status or register', url: 'https://www.votetexas.gov', category: 'services' },
    { name: 'Waxahachie Chamber of Commerce', description: 'Local business support', url: 'https://www.waxahachiechamber.com', category: 'community' },
    { name: 'Ellis County SPCA', description: 'Animal services', url: 'https://www.elliscountyspca.org', category: 'community' },
    { name: 'Nicholas P. Sims Library', description: 'Public library in Waxahachie', url: 'https://www.waxahachie.com/295/Library', category: 'community' },
];
